Adding CI to PlayerKit
vimeo/PlayerKit pull request #2
Opened 2017-03-15 16:34 UTC by MathiasGr

Here's the setup for CI @ghking.

2017-03-15 16:37 UTC, ghking commented
@MathiasGr Dope thank you!

2017-03-22 21:05 UTC, wilrnh requested changes

2017-03-22 21:05 UTC, wilrnh commented on fastlane/Fastfile
> +    ensure_xcode_version(version: "8.0")
Just bump this up to 8.2.1

2017-03-22 21:05 UTC, wilrnh commented on circle.yml
> +    version: 8.0
Just bump this to 8.2.1

2017-03-22 21:05 UTC, wilrnh commented on circle.yml
> +        - "Pods"
Is this really the path to the Pods folder, maybe its actually `Example/Pods`?

2017-03-22 21:05 UTC, wilrnh commented on circle.yml
> +        - "vendor/bundle"
`bundle install` doesnt create `vendor/bundle`; use `bundle install --deployment` for that

2017-03-22 21:05 UTC, wilrnh commented on fastlane/Fastfile
> +  lane :build_example do |options|
no need for build_example, :test already runs "build" and "test"

2017-03-22 21:05 UTC, wilrnh commented on .gitignore
> +xcodebuild.log
only build_example creates xcodebuild.log, see circle.yml

2017-03-22 21:05 UTC, wilrnh commented on circle.yml
> +    - "xcodebuild.log"
nope, see .gitignore

2017-03-22 21:05 UTC, wilrnh commented on circle.yml
> +    - "build/Logs"
build/Logs are the xcactivity logs, we'd also need to save the `PlayerKit_Example-PlayerKit-Example.log` here too

2017-03-22 21:05 UTC, wilrnh commented on fastlane/Fastfile
> +      danger(use_bundle_exec: false)
:o Gotta get a Dangerfile for this to work...

2017-03-22 21:05 UTC, wilrnh commented on fastlane/Fastfile
> +      configuration: "Debug",
Sure you want to test Debug not Release?

2017-03-23 18:46 UTC, MathiasGr commented on fastlane/Fastfile
> +      danger(use_bundle_exec: false)
done

2017-03-23 18:46 UTC, MathiasGr commented on fastlane/Fastfile
> +      configuration: "Debug",
Not sure about this one. @ghking do you have any idea?

2017-03-23 18:47 UTC, MathiasGr commented
@wilrnh Addressed issues

2017-03-27 20:41 UTC, ghking commented
@wilrnh @MathiasGr bump :)

2017-03-27 23:00 UTC, wilrnh commented on fastlane/Fastfile
> +      configuration: "Debug",
@MathiasGr lets switch this to Release. I expect when this is a cocoapod we'll want it to build with release settings.

2017-03-27 23:03 UTC, wilrnh approved these changes
🔥

2017-04-11 17:04 UTC, ghking commented
@wilrnh @MathiasGr Guys can we merge this?

2017-05-08 20:58 UTC, wilrnh commented
😱

2017-05-08 20:59 UTC, merged