AF-210: Swift 4
vimeo/PlayerKit pull request #21
Opened 2017-11-29 22:05 UTC by ghking

#### Ticket

https://vimean.atlassian.net/browse/AF-210

#### Issue Summary

Convert to Swift 4.

#### Implementation Summary

Converted to Swift 4. Changed some API around fill mode to further abstract AVPlayer implementation. Added `@objc` annotations where applicable.

#### How to Test

Make sure everything works as expected.

2017-11-29 22:20 UTC, cameo-github commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/PlayerKit/36)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2017-12-07 19:22 UTC, mikew-personal requested changes

2017-12-07 19:22 UTC, mikew-personal commented on fastlane/Fastfile
> +    ensure_xcode_version(version: "9.0.1")
is there a reason we need to bump up our required Xcode version?  The rest of our builds all require 9.0.

2017-12-07 19:22 UTC, mikew-personal commented on PlayerKit/Classes/RegularPlayer.swift
> +    @objc open func set(_ asset: AVAsset)
are we marking functions with @objc as we need them in our projects?  We should probably add @objc to all our public functions so we're fully compatible with Objective-C in case third parties need it?

2017-12-07 19:30 UTC, mikew-personal approved these changes

2017-12-07 21:00 UTC, merged